name: Flutter Tests

on:
  pull_request:
    branches:
      - main # Replace with your default branch if it's not 'main'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable' # Specify Flutter version or use 'stable'

    # Install dependencies
    - name: Install dependencies
      run: flutter pub get

    # Run tests
    - name: Run tests
      run: flutter test
